### PR TITLE
upgrade to androidX

### PR DESCRIPTION
**Pull request by juicycleff**
Upgrade library to support AndroidX

### CODE REVIEW

**Comment by YouCii** [comment]
Great, I am bothered by this problem.

**Comment by juicycleff** [comment]
Me too, for now, I am using my repo, can't wait for it to be merged in

**Comment by pichillilorenzo** [comment]
Thanks @juicycleff! I will release the new version 1.0.0 because, as said [here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#for-plugin-maintainers-migrating-a-flutter-plugin-to-androidx):

> Make sure to increment the major version of your plugin for this change and clearly document it in your plugin’s changelog. This breaking change requires manual migration for users to fix. Pub treats digits differently depending on whether a plugin is pre- or post-1.0.0. The very first digit is the major version for plugins that are at or above 1.0.0. For plugins below 1.0.0, the middle digit is considered to the major version.

**Comment by pichillilorenzo** [comment]
I released the new version **1.0.0**!

**Pull request merged**
